using System;
using System.Text;

namespace Atc.Rest.ApiGenerator.Helpers
{
    internal static class GenerateCodeHelper
    {
        internal static void AppendNamespaceComment(StringBuilder sb, string toolNameAndVersion)
        {
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine($"// This code was auto-generated by {toolNameAndVersion}.");
            sb.AppendLine("//");
            sb.AppendLine("// Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("// the code is regenerated.");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("//--");
        }

        internal static void AppendGeneratedCodeAttribute(StringBuilder sb, string toolName, Version toolVersion)
        {
            sb.AppendLine(4, $"[GeneratedCode(\"{toolName}\", \"{toolVersion}\")]");
        }
    }
}