using System.CodeDom.Compiler;
using System.Collections.Generic;

//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 1.0.181.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Users
{
    /// <summary>
    /// A list of users.
    /// </summary>
    [GeneratedCode("ApiGenerator", "1.0.181.0")]
    public class Users
    {
        /// <summary>
        /// A list of User.
        /// </summary>
        public List<User> UserList { get; set; } = new List<User>();
    }
}