using System.CodeDom.Compiler;
using System.Net;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;

//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 1.0.0.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
//
// ReSharper disable once CheckNamespace
namespace Demo.Api.Generated
{
    [GeneratedCode("ApiGenerator", "1.0.0.0")]
    internal static class ResultFactory
    {
        internal static ProblemDetails CreateProblemDetails(HttpStatusCode statusCode, string? message)
        {
            var result = new ProblemDetails();
            result.Status = (int)statusCode;
            result.Detail = message;
            return result;
        }

        internal static ContentResult CreateContentResultWithProblemDetails(HttpStatusCode statusCode, string? message, string contentType = "application/json")
        {
            return new ContentResult { ContentType = contentType, StatusCode = (int)statusCode, Content = JsonSerializer.Serialize(CreateProblemDetails(statusCode, message)) } ;
        }

        internal static ContentResult CreateContentResult(HttpStatusCode statusCode, string? message, string contentType = "application/json")
        {
            return new ContentResult { ContentType = contentType, StatusCode = (int)statusCode, Content = JsonSerializer.Serialize(message) } ;
        }
    }
}