using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

//------------------------------------------------------------------------------
// This code was auto-generated by Atc.Rest.ApiGenerator 1.0.0.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
//
// ReSharper disable once CheckNamespace
namespace Demo.Api.Generated.Contracts.Users
{
    /// <summary>
    /// Parameters for operation request.
    /// Description: Create a new user.
    /// Operation: PostUsers.
    /// Area: Users.
    /// </summary>
    public class PostUsersParameters
    {
        /// <summary>
        /// Request to create a user.
        /// </summary>
        [FromBody]
        [Required]
        public CreateUserRequest Request { get; set; }

        /// <summary>
        /// Converts to string.
        /// </summary>
        public override string ToString()
        {
            return $"{nameof(Request)}: ({Request})";
        }
    }
}