using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 1.0.0.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
//
// ReSharper disable once CheckNamespace
namespace Demo.Api.Generated.Contracts.Orders
{
    /// <summary>
    /// Parameters for operation request.
    /// Description: Update part of order by id.
    /// Operation: PatchOrdersId.
    /// Area: Orders.
    /// </summary>
    public class PatchOrdersIdParameters
    {
        /// <summary>
        /// The id of the order to retrieve.
        /// </summary>
        [FromRoute(Name = "id")]
        [Required]
        public string Id { get; set; }

        /// <summary>
        /// The myTestHeader special key.
        /// </summary>
        [FromHeader(Name = "myTestHeader")]
        [Required]
        public string MyTestHeader { get; set; }

        /// <summary>
        /// Request to update an order.
        /// </summary>
        [FromBody]
        [Required]
        public UpdateOrderRequest Request { get; set; }

        /// <summary>
        /// Converts to string.
        /// </summary>
        public override string ToString()
        {
            return $"{nameof(Id)}: {Id}, {nameof(MyTestHeader)}: {MyTestHeader}, {nameof(Request)}: ({Request})";
        }
    }
}