//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atc.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string AppTypeApplication {
            get {
                return ResourceManager.GetString("AppTypeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string AppTypeService {
            get {
                return ResourceManager.GetString("AppTypeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of Substance.
        /// </summary>
        public static string BaseUnitTypeAmountOfSubstance {
            get {
                return ResourceManager.GetString("BaseUnitTypeAmountOfSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Current.
        /// </summary>
        public static string BaseUnitTypeElectricCurrent {
            get {
                return ResourceManager.GetString("BaseUnitTypeElectricCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string BaseUnitTypeLength {
            get {
                return ResourceManager.GetString("BaseUnitTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminous Intensity.
        /// </summary>
        public static string BaseUnitTypeLuminousIntensity {
            get {
                return ResourceManager.GetString("BaseUnitTypeLuminousIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string BaseUnitTypeMass {
            get {
                return ResourceManager.GetString("BaseUnitTypeMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermodynamic Temperature.
        /// </summary>
        public static string BaseUnitTypeThermodynamicTemperature {
            get {
                return ResourceManager.GetString("BaseUnitTypeThermodynamicTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string BaseUnitTypeTime {
            get {
                return ResourceManager.GetString("BaseUnitTypeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string BooleanOperatorTypeAnd {
            get {
                return ResourceManager.GetString("BooleanOperatorTypeAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near.
        /// </summary>
        public static string BooleanOperatorTypeNear {
            get {
                return ResourceManager.GetString("BooleanOperatorTypeNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string BooleanOperatorTypeNot {
            get {
                return ResourceManager.GetString("BooleanOperatorTypeNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string BooleanOperatorTypeOr {
            get {
                return ResourceManager.GetString("BooleanOperatorTypeOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string CollectionActionTypeAdded {
            get {
                return ResourceManager.GetString("CollectionActionTypeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string CollectionActionTypeCleared {
            get {
                return ResourceManager.GetString("CollectionActionTypeCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string CollectionActionTypeLoaded {
            get {
                return ResourceManager.GetString("CollectionActionTypeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string CollectionActionTypeRemoved {
            get {
                return ResourceManager.GetString("CollectionActionTypeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string CollectionActionTypeSaved {
            get {
                return ResourceManager.GetString("CollectionActionTypeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string CollectionActionTypeUpdated {
            get {
                return ResourceManager.GetString("CollectionActionTypeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string DateTimeDiffCompareTypeDays {
            get {
                return ResourceManager.GetString("DateTimeDiffCompareTypeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string DateTimeDiffCompareTypeHours {
            get {
                return ResourceManager.GetString("DateTimeDiffCompareTypeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        public static string DateTimeDiffCompareTypeMilliseconds {
            get {
                return ResourceManager.GetString("DateTimeDiffCompareTypeMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string DateTimeDiffCompareTypeMinutes {
            get {
                return ResourceManager.GetString("DateTimeDiffCompareTypeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartal.
        /// </summary>
        public static string DateTimeDiffCompareTypeQuartal {
            get {
                return ResourceManager.GetString("DateTimeDiffCompareTypeQuartal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string DateTimeDiffCompareTypeSeconds {
            get {
                return ResourceManager.GetString("DateTimeDiffCompareTypeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticks.
        /// </summary>
        public static string DateTimeDiffCompareTypeTicks {
            get {
                return ResourceManager.GetString("DateTimeDiffCompareTypeTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string DateTimeDiffCompareTypeYear {
            get {
                return ResourceManager.GetString("DateTimeDiffCompareTypeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- All --.
        /// </summary>
        public static string DropDownFirstItemTypeIncludeAll {
            get {
                return ResourceManager.GetString("DropDownFirstItemTypeIncludeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        public static string DropDownFirstItemTypePleaseSelect {
            get {
                return ResourceManager.GetString("DropDownFirstItemTypePleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string FileSystemWatcherChangeTypeAdded {
            get {
                return ResourceManager.GetString("FileSystemWatcherChangeTypeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string FileSystemWatcherChangeTypeChanged {
            get {
                return ResourceManager.GetString("FileSystemWatcherChangeTypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string FileSystemWatcherChangeTypeDeleted {
            get {
                return ResourceManager.GetString("FileSystemWatcherChangeTypeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed.
        /// </summary>
        public static string FileSystemWatcherChangeTypeRenamed {
            get {
                return ResourceManager.GetString("FileSystemWatcherChangeTypeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ForwardReverseTypeForward {
            get {
                return ResourceManager.GetString("ForwardReverseTypeForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string ForwardReverseTypeReverse {
            get {
                return ResourceManager.GetString("ForwardReverseTypeReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string IdentityRoleTypeAdmin {
            get {
                return ResourceManager.GetString("IdentityRoleTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        public static string IdentityRoleTypeAnonymous {
            get {
                return ResourceManager.GetString("IdentityRoleTypeAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Administrator.
        /// </summary>
        public static string IdentityRoleTypeSuperAdmin {
            get {
                return ResourceManager.GetString("IdentityRoleTypeSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User.
        /// </summary>
        public static string IdentityRoleTypeSuperUser {
            get {
                return ResourceManager.GetString("IdentityRoleTypeSuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string IdentityRoleTypeUser {
            get {
                return ResourceManager.GetString("IdentityRoleTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string InsertRemoveTypeInsert {
            get {
                return ResourceManager.GetString("InsertRemoveTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string InsertRemoveTypeRemove {
            get {
                return ResourceManager.GetString("InsertRemoveTypeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LeftRightTypeLeft {
            get {
                return ResourceManager.GetString("LeftRightTypeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string LeftRightTypeRight {
            get {
                return ResourceManager.GetString("LeftRightTypeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Category Type.
        /// </summary>
        public static string LogCategoryType {
            get {
                return ResourceManager.GetString("LogCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string LogCategoryTypeAudit {
            get {
                return ResourceManager.GetString("LogCategoryTypeAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string LogCategoryTypeCritical {
            get {
                return ResourceManager.GetString("LogCategoryTypeCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string LogCategoryTypeDebug {
            get {
                return ResourceManager.GetString("LogCategoryTypeDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LogCategoryTypeError {
            get {
                return ResourceManager.GetString("LogCategoryTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string LogCategoryTypeInformation {
            get {
                return ResourceManager.GetString("LogCategoryTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string LogCategoryTypeSecurity {
            get {
                return ResourceManager.GetString("LogCategoryTypeSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string LogCategoryTypeService {
            get {
                return ResourceManager.GetString("LogCategoryTypeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        public static string LogCategoryTypeTrace {
            get {
                return ResourceManager.GetString("LogCategoryTypeTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string LogCategoryTypeUI {
            get {
                return ResourceManager.GetString("LogCategoryTypeUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LogCategoryTypeWarning {
            get {
                return ResourceManager.GetString("LogCategoryTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OnOffTypeOff {
            get {
                return ResourceManager.GetString("OnOffTypeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnOffTypeOn {
            get {
                return ResourceManager.GetString("OnOffTypeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string QualityCategoryTypeExcellent {
            get {
                return ResourceManager.GetString("QualityCategoryTypeExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        public static string QualityCategoryTypeFair {
            get {
                return ResourceManager.GetString("QualityCategoryTypeFair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string QualityCategoryTypeGood {
            get {
                return ResourceManager.GetString("QualityCategoryTypeGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect.
        /// </summary>
        public static string QualityCategoryTypePerfect {
            get {
                return ResourceManager.GetString("QualityCategoryTypePerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string QualityCategoryTypePoor {
            get {
                return ResourceManager.GetString("QualityCategoryTypePoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string QualityCategoryTypeVeryGood {
            get {
                return ResourceManager.GetString("QualityCategoryTypeVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Poor.
        /// </summary>
        public static string QualityCategoryTypeVeryPoor {
            get {
                return ResourceManager.GetString("QualityCategoryTypeVeryPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could have.
        /// </summary>
        public static string RequestPriorityLevelCouldHave {
            get {
                return ResourceManager.GetString("RequestPriorityLevelCouldHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have.
        /// </summary>
        public static string RequestPriorityLevelMustHave {
            get {
                return ResourceManager.GetString("RequestPriorityLevelMustHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have now.
        /// </summary>
        public static string RequestPriorityLevelMustHaveNow {
            get {
                return ResourceManager.GetString("RequestPriorityLevelMustHaveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should have.
        /// </summary>
        public static string RequestPriorityLevelShouldHave {
            get {
                return ResourceManager.GetString("RequestPriorityLevelShouldHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won&apos;t have.
        /// </summary>
        public static string RequestPriorityLevelWonotHave {
            get {
                return ResourceManager.GetString("RequestPriorityLevelWonotHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string SeverityLevelCritical {
            get {
                return ResourceManager.GetString("SeverityLevelCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string SeverityLevelHigh {
            get {
                return ResourceManager.GetString("SeverityLevelHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string SeverityLevelLow {
            get {
                return ResourceManager.GetString("SeverityLevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string SeverityLevelMedium {
            get {
                return ResourceManager.GetString("SeverityLevelMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string SortDirectionTypeAscending {
            get {
                return ResourceManager.GetString("SortDirectionTypeAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string SortDirectionTypeDescending {
            get {
                return ResourceManager.GetString("SortDirectionTypeDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TriggerActionTypeDelete {
            get {
                return ResourceManager.GetString("TriggerActionTypeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string TriggerActionTypeInsert {
            get {
                return ResourceManager.GetString("TriggerActionTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string TriggerActionTypeUpdate {
            get {
                return ResourceManager.GetString("TriggerActionTypeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string UpDownTypeDown {
            get {
                return ResourceManager.GetString("UpDownTypeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string UpDownTypeUp {
            get {
                return ResourceManager.GetString("UpDownTypeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string YesNoTypeNo {
            get {
                return ResourceManager.GetString("YesNoTypeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesNoTypeYes {
            get {
                return ResourceManager.GetString("YesNoTypeYes", resourceCulture);
            }
        }
    }
}
