//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atc.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string _Language {
            get {
                return ResourceManager.GetString("_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrikaans.
        /// </summary>
        public static string Afrikaans {
            get {
                return ResourceManager.GetString("Afrikaans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        public static string Albanian {
            get {
                return ResourceManager.GetString("Albanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American.
        /// </summary>
        public static string American {
            get {
                return ResourceManager.GetString("American", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amharic.
        /// </summary>
        public static string Amharic {
            get {
                return ResourceManager.GetString("Amharic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian.
        /// </summary>
        public static string Armenian {
            get {
                return ResourceManager.GetString("Armenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assamese.
        /// </summary>
        public static string Assamese {
            get {
                return ResourceManager.GetString("Assamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijani.
        /// </summary>
        public static string Azerbaijani {
            get {
                return ResourceManager.GetString("Azerbaijani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangla.
        /// </summary>
        public static string Bangla {
            get {
                return ResourceManager.GetString("Bangla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bashkir.
        /// </summary>
        public static string Bashkir {
            get {
                return ResourceManager.GetString("Bashkir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basque.
        /// </summary>
        public static string Basque {
            get {
                return ResourceManager.GetString("Basque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian.
        /// </summary>
        public static string Belarusian {
            get {
                return ResourceManager.GetString("Belarusian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnian.
        /// </summary>
        public static string Bosnian {
            get {
                return ResourceManager.GetString("Bosnian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breton.
        /// </summary>
        public static string Breton {
            get {
                return ResourceManager.GetString("Breton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burmese.
        /// </summary>
        public static string Burmese {
            get {
                return ResourceManager.GetString("Burmese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string Catalan {
            get {
                return ResourceManager.GetString("Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Atlas Tamazight.
        /// </summary>
        public static string CentralAtlasTamazight {
            get {
                return ResourceManager.GetString("CentralAtlasTamazight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsican.
        /// </summary>
        public static string Corsican {
            get {
                return ResourceManager.GetString("Corsican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Danish {
            get {
                return ResourceManager.GetString("Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divehi.
        /// </summary>
        public static string Divehi {
            get {
                return ResourceManager.GetString("Divehi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzongkha.
        /// </summary>
        public static string Dzongkha {
            get {
                return ResourceManager.GetString("Dzongkha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edo.
        /// </summary>
        public static string Edo {
            get {
                return ResourceManager.GetString("Edo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string Estonian {
            get {
                return ResourceManager.GetString("Estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroese.
        /// </summary>
        public static string Faroese {
            get {
                return ResourceManager.GetString("Faroese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filipino.
        /// </summary>
        public static string Filipino {
            get {
                return ResourceManager.GetString("Filipino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string Finnish {
            get {
                return ResourceManager.GetString("Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulah.
        /// </summary>
        public static string Fulah {
            get {
                return ResourceManager.GetString("Fulah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galician.
        /// </summary>
        public static string Galician {
            get {
                return ResourceManager.GetString("Galician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string Georgian {
            get {
                return ResourceManager.GetString("Georgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarani.
        /// </summary>
        public static string Guarani {
            get {
                return ResourceManager.GetString("Guarani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujarati.
        /// </summary>
        public static string Gujarati {
            get {
                return ResourceManager.GetString("Gujarati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawaiian.
        /// </summary>
        public static string Hawaiian {
            get {
                return ResourceManager.GetString("Hawaiian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        public static string Hebrew {
            get {
                return ResourceManager.GetString("Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibibio.
        /// </summary>
        public static string Ibibio {
            get {
                return ResourceManager.GetString("Ibibio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        public static string Icelandic {
            get {
                return ResourceManager.GetString("Icelandic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igbo.
        /// </summary>
        public static string Igbo {
            get {
                return ResourceManager.GetString("Igbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inari Sami.
        /// </summary>
        public static string Inari_Sami {
            get {
                return ResourceManager.GetString("Inari Sami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inuktitut.
        /// </summary>
        public static string Inuktitut {
            get {
                return ResourceManager.GetString("Inuktitut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        public static string Irish {
            get {
                return ResourceManager.GetString("Irish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isiXhosa.
        /// </summary>
        public static string IsiXhosa {
            get {
                return ResourceManager.GetString("IsiXhosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isiZulu.
        /// </summary>
        public static string IsiZulu {
            get {
                return ResourceManager.GetString("IsiZulu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalaallisut.
        /// </summary>
        public static string Kalaallisut {
            get {
                return ResourceManager.GetString("Kalaallisut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kannada.
        /// </summary>
        public static string Kannada {
            get {
                return ResourceManager.GetString("Kannada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kashmiri.
        /// </summary>
        public static string Kashmiri {
            get {
                return ResourceManager.GetString("Kashmiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakh.
        /// </summary>
        public static string Kazakh {
            get {
                return ResourceManager.GetString("Kazakh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string Khmer {
            get {
                return ResourceManager.GetString("Khmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinyarwanda.
        /// </summary>
        public static string Kinyarwanda {
            get {
                return ResourceManager.GetString("Kinyarwanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiswahili.
        /// </summary>
        public static string Kiswahili {
            get {
                return ResourceManager.GetString("Kiswahili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konkani.
        /// </summary>
        public static string Konkani {
            get {
                return ResourceManager.GetString("Konkani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyz.
        /// </summary>
        public static string Kyrgyz {
            get {
                return ResourceManager.GetString("Kyrgyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        public static string Lao {
            get {
                return ResourceManager.GetString("Lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string Latvian {
            get {
                return ResourceManager.GetString("Latvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        public static string Lithuanian {
            get {
                return ResourceManager.GetString("Lithuanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Sorbian.
        /// </summary>
        public static string Lower_Sorbian {
            get {
                return ResourceManager.GetString("Lower Sorbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lule Sami.
        /// </summary>
        public static string Lule_Sami {
            get {
                return ResourceManager.GetString("Lule Sami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourgish.
        /// </summary>
        public static string Luxembourgish {
            get {
                return ResourceManager.GetString("Luxembourgish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian.
        /// </summary>
        public static string Macedonian {
            get {
                return ResourceManager.GetString("Macedonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malay.
        /// </summary>
        public static string Malay {
            get {
                return ResourceManager.GetString("Malay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malayalam.
        /// </summary>
        public static string Malayalam {
            get {
                return ResourceManager.GetString("Malayalam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltese.
        /// </summary>
        public static string Maltese {
            get {
                return ResourceManager.GetString("Maltese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maori.
        /// </summary>
        public static string Maori {
            get {
                return ResourceManager.GetString("Maori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapuche.
        /// </summary>
        public static string Mapuche {
            get {
                return ResourceManager.GetString("Mapuche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathi.
        /// </summary>
        public static string Marathi {
            get {
                return ResourceManager.GetString("Marathi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohawk.
        /// </summary>
        public static string Mohawk {
            get {
                return ResourceManager.GetString("Mohawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian.
        /// </summary>
        public static string Mongolian {
            get {
                return ResourceManager.GetString("Mongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepali.
        /// </summary>
        public static string Nepali {
            get {
                return ResourceManager.GetString("Nepali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Sami.
        /// </summary>
        public static string Northern_Sami {
            get {
                return ResourceManager.GetString("Northern Sami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string Norwegian {
            get {
                return ResourceManager.GetString("Norwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian Bokmål.
        /// </summary>
        public static string Norwegian_Bokmål {
            get {
                return ResourceManager.GetString("Norwegian Bokmål", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian Nynorsk.
        /// </summary>
        public static string Norwegian_Nynorsk {
            get {
                return ResourceManager.GetString("Norwegian Nynorsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occitan.
        /// </summary>
        public static string Occitan {
            get {
                return ResourceManager.GetString("Occitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odia.
        /// </summary>
        public static string Odia {
            get {
                return ResourceManager.GetString("Odia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oromo.
        /// </summary>
        public static string Oromo {
            get {
                return ResourceManager.GetString("Oromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pashto.
        /// </summary>
        public static string Pashto {
            get {
                return ResourceManager.GetString("Pashto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punjabi.
        /// </summary>
        public static string Punjabi {
            get {
                return ResourceManager.GetString("Punjabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romansh.
        /// </summary>
        public static string Romansh {
            get {
                return ResourceManager.GetString("Romansh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakha.
        /// </summary>
        public static string Sakha {
            get {
                return ResourceManager.GetString("Sakha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanskrit.
        /// </summary>
        public static string Sanskrit {
            get {
                return ResourceManager.GetString("Sanskrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scottish Gaelic.
        /// </summary>
        public static string ScottishGaelic {
            get {
                return ResourceManager.GetString("ScottishGaelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesotho.
        /// </summary>
        public static string Sesotho {
            get {
                return ResourceManager.GetString("Sesotho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesotho sa Leboa.
        /// </summary>
        public static string SesothoSaLeboa {
            get {
                return ResourceManager.GetString("SesothoSaLeboa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setswana.
        /// </summary>
        public static string Setswana {
            get {
                return ResourceManager.GetString("Setswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sindhi.
        /// </summary>
        public static string Sindhi {
            get {
                return ResourceManager.GetString("Sindhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhala.
        /// </summary>
        public static string Sinhala {
            get {
                return ResourceManager.GetString("Sinhala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skolt Sami.
        /// </summary>
        public static string Skolt_Sami {
            get {
                return ResourceManager.GetString("Skolt Sami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string Slovak {
            get {
                return ResourceManager.GetString("Slovak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        public static string Slovenian {
            get {
                return ResourceManager.GetString("Slovenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somali.
        /// </summary>
        public static string Somali {
            get {
                return ResourceManager.GetString("Somali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Sami.
        /// </summary>
        public static string SouthernSami {
            get {
                return ResourceManager.GetString("SouthernSami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss German.
        /// </summary>
        public static string SwissGerman {
            get {
                return ResourceManager.GetString("SwissGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syriac.
        /// </summary>
        public static string Syriac {
            get {
                return ResourceManager.GetString("Syriac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        public static string Tamil {
            get {
                return ResourceManager.GetString("Tamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatar.
        /// </summary>
        public static string Tatar {
            get {
                return ResourceManager.GetString("Tatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telugu.
        /// </summary>
        public static string Telugu {
            get {
                return ResourceManager.GetString("Telugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibetan.
        /// </summary>
        public static string Tibetan {
            get {
                return ResourceManager.GetString("Tibetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tigrinya.
        /// </summary>
        public static string Tigrinya {
            get {
                return ResourceManager.GetString("Tigrinya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmen.
        /// </summary>
        public static string Turkmen {
            get {
                return ResourceManager.GetString("Turkmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Sorbian.
        /// </summary>
        public static string UpperSorbian {
            get {
                return ResourceManager.GetString("UpperSorbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        public static string Urdu {
            get {
                return ResourceManager.GetString("Urdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyghur.
        /// </summary>
        public static string Uyghur {
            get {
                return ResourceManager.GetString("Uyghur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek.
        /// </summary>
        public static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda.
        /// </summary>
        public static string Venda {
            get {
                return ResourceManager.GetString("Venda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welsh.
        /// </summary>
        public static string Welsh {
            get {
                return ResourceManager.GetString("Welsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Frisian.
        /// </summary>
        public static string WesternFrisian {
            get {
                return ResourceManager.GetString("WesternFrisian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolof.
        /// </summary>
        public static string Wolof {
            get {
                return ResourceManager.GetString("Wolof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xitsonga.
        /// </summary>
        public static string Xitsonga {
            get {
                return ResourceManager.GetString("Xitsonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yi.
        /// </summary>
        public static string Yi {
            get {
                return ResourceManager.GetString("Yi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoruba.
        /// </summary>
        public static string Yoruba {
            get {
                return ResourceManager.GetString("Yoruba", resourceCulture);
            }
        }
    }
}
