using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 1.0.216.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Items
{
    /// <summary>
    /// Parameters for operation request.
    /// Description: Create a new item.
    /// Operation: CreateItem.
    /// Area: Items.
    /// </summary>
    [GeneratedCode("ApiGenerator", "1.0.216.0")]
    public class CreateItemParameters
    {
        [FromBody]
        [Required]
        public CreateItemRequest Request { get; set; }

        /// <summary>
        /// Converts to string.
        /// </summary>
        public override string ToString()
        {
            return $"{nameof(Request)}: ({Request})";
        }
    }
}