<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <PackageId>Atc.XUnit</PackageId>
    <PackageTags>xunit;test</PackageTags>
    <Description>Atc.XUnit is a collection of helper method for code compliance of documentation and tests.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.7.0" />
    <PackageReference Include="ICSharpCode.Decompiler" Version="11.0.0.9375" />
    <PackageReference Include="Mono.Reflection" Version="2.0.0">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="xunit.v3.assert" Version="4.0.0" />
    <PackageReference Include="xunit.v3.common" Version="4.0.0" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atc.CodeDocumentation\Atc.CodeDocumentation.csproj" />
    <ProjectReference Include="..\Atc\Atc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Atc.XUnit.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>