using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;

//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 1.0.216.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.RouteWithDash
{
    /// <summary>
    /// Domain Interface for RequestHandler.
    /// Description: Your GET endpoint.
    /// Operation: GetRouteWithDash.
    /// Area: RouteWithDash.
    /// </summary>
    [GeneratedCode("ApiGenerator", "1.0.216.0")]
    public interface IGetRouteWithDashHandler
    {
        /// <summary>
        /// Execute method.
        /// </summary>
        /// <param name="cancellationToken">The cancellation token.</param>
        Task<GetRouteWithDashResult> ExecuteAsync(CancellationToken cancellationToken = default);
    }
}